rename r_cg_cgc.c               boot_r_cg_cgc.c
rename r_cg_cgc.h 				boot_r_cg_cgc.h
rename r_cg_cgc_user.c 			boot_r_cg_cgc_user.c
rename r_cg_macrodriver.h 		boot_r_cg_macrodriver.h
rename r_cg_port.c 				boot_r_cg_port.c
rename r_cg_port.h 				boot_r_cg_port.h
rename r_cg_port_user.c 		boot_r_cg_port_user.c
rename r_cg_serial.c 			boot_r_cg_serial.c
rename r_cg_serial.h 			boot_r_cg_serial.h
rename r_cg_serial_user.c 		boot_r_cg_serial_user.c
rename r_cg_timer.c 			boot_r_cg_timer.c
rename r_cg_timer.h 			boot_r_cg_timer.h
rename r_cg_timer_user.c 		boot_r_cg_timer_user.c
rename r_cg_userdefine.h 		boot_r_cg_userdefine.h
rename r_cg_wdt.c 				boot_r_cg_wdt.c
rename r_cg_wdt.h 				boot_r_cg_wdt.h
rename r_cg_wdt_user.c 			boot_r_cg_wdt_user.c
rename r_main.c 				boot_r_main.c
rename r_systeminit.c 			boot_r_systeminit.c